# ch08. 예외 처리

## try-catch-finally-return

```java
class Test {  
    public static void main(String[] args) {  
       System.out.println("result = " + test());  
    }  
  
    private static String test() {  
       String message = "";  
       try {  
          message = "Try";  
          System.out.println(message);  
          return message;  
       } catch (Exception e) {  
          message = "Exception";  
          System.out.println(message);
       } finally {  
          message = "Finally";  
          System.out.println(message);  
       }  
       return message; // 오류는 나지 않지만 실행되지 않음
    }  
}
/*
Try
Finally
result = Try
*/
```

```java
class Test {  
    public static void main(String[] args) {  
       System.out.println("result = " + test());  
    }  
  
    private static String test() {  
       String message = "";  
       try {  
          message = "Try";  
          System.out.println(message); 
          return message;  
       } catch (Exception e) {  
          message = "Exception";  
          System.out.println(message);  
       } finally {  
          message = "Finally";  
          System.out.println(message);  
          return message;
       }  
       //return message; unreachable statement
    }  
}
/*
Try
Finally
result = Finally
*/
```

```java
class Test {  
    public static void main(String[] args) {  
       System.out.println("result = " + test());  
    }  
  
    private static String test() {  
       String message = "";  
       try {  
          message = "Try";  
          System.out.println(message);  
          int i = 1 / 0;
          return message;  
       } catch (Exception e) {  
          message = "Exception";  
          System.out.println(message);  
		  return message;
       } finally {  
          message = "Finally";  
          System.out.println(message);  
       }
       //return message; unreachable statement
    }  
}
/*
Try
Exception
Finally 
result = Exception
*/
```

```java
class Test {  
    public static void main(String[] args) {  
       System.out.println("result = " + test());  
    }  
  
    private static String test() {  
       String message = "";  
       try {  
          message = "Try";  
          System.out.println(message);  
          int i = 1 / 0;
          return message;  
       } catch (Exception e) {  
          message = "Exception";  
          System.out.println(message);  
		  return message;
       } finally {  
          message = "Finally";  
          System.out.println(message);  
          return message;
       }
    }  
}
/*
Try
Exception
Finally
result = Finally
*/
```


## try-with-resources
JDK 7에 추가된 `try-with-resources` 문법을 이용하면 `AutoCloseable` 인터페이스[^1]를 구현한 자원에 대해 자동으로 자원을 반납한다.
`try-with-resources` 문법은 기존 `try-finally`에서 발생할 수 있는 예외의 스택 트레이스 누락, 자원 반납의 누락을 언어 차원에서 자동으로 해결해준다.

```java
try (InputStream is = new FileInputStream("test.txt");
	 InputStream bs = new DataInputStream(is)) {
	// do something...
} catch (Exception e) {
	// do something...
}
```

기존의 `try-with-resources` 문법은 try 블럭 밖에서 선언된 변수를 직접 사용하지 못했는데 JDK 9부터는 해당 변수를 직접 사용할 수 있도록 개선되었다. 

```java
// < JKD 9
BufferedReader br1 = new BufferedReader(new FileReader("test1.txt"));
BufferedReader br2 = new BufferedReader(new FileReader("test2.txt"));
try (BufferedReader b1 = br1;
	 BufferedReader b2 = br2) {
	// do something...
}

// JDK 9 ~
BufferedReader br1 = new BufferedReader(new FileReader("test1.txt"));
BufferedReader br2 = new BufferedReader(new FileReader("test2.txt"));
try (br1; br2) {
	// do something...
}
```


[^1]: 기존의 `Closeable` 인터페이스의 부모 인터페이스로 지정하여 하위 호환성을 챙겼다.